[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_relay_receiving_node_not_connected_directly_to_relaying_node with id: 2024-12-25_19-37-31__bdaa7c46-9caa-43de-be23-70ba1fe3d16e
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.light_push:light_push.py:28 Running fixture setup: light_push_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-12-25_19-37-31__bdaa7c46-9caa-43de-be23-70ba1fe3d16e__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2024-12-25_19-37-31__bdaa7c46-9caa-43de-be23-70ba1fe3d16e__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node3_2024-12-25_19-37-31__bdaa7c46-9caa-43de-be23-70ba1fe3d16e__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.steps.relay:relay.py:28 Running fixture setup: relay_setup
[35mDEBUG   [0m src.steps.store:store.py:31 Running fixture setup: store_setup
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.53.201
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['1959', '1960', '1961', '1962', '1963']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 1959:1959 -p 1960:1960 -p 1961:1961 -p 1962:1962 -p 1963:1963 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=1961 --rest-port=1959 --tcp-port=1960 --discv5-udp-port=1962 --rest-address=0.0.0.0 --nat=extip:172.18.53.201 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=adfafea5dedb43d95fdfda0fbe4ba83ba58cd9ccef1c3cd313ebeecacdbaa2d8 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=1963 --metrics-logging=true --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.53.201 waku 167f7bb335502e81ade2a7c88ca4d53c154a31e2f2842cc9452bb8220f73ccf4
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 167f7bb33550. Setting up logs at ./log/docker/node1_2024-12-25_19-37-31__bdaa7c46-9caa-43de-be23-70ba1fe3d16e__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 1959
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:1959/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:1959/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.53.201/tcp/1960/p2p/16Uiu2HAm3DZeuwUC1DnrDAgW7qdpzL7h9Ug9P8m5fN2U5L7ULAjQ","/ip4/172.18.53.201/tcp/1961/ws/p2p/16Uiu2HAm3DZeuwUC1DnrDAgW7qdpzL7h9Ug9P8m5fN2U5L7ULAjQ"],"enrUri":"enr:-L24QGUYKNfynrtq0MrjvP8jx-nYiofUHeQNybiraV5o9aMyeQPFnUPuh4pwKBzL8a0k8DK6HwXeGrSWutXd-0tO9_sCgmlkgnY0gmlwhKwSNcmKbXVsdGlhZGRyc5YACASsEjXJBgeoAAoErBI1yQYHqd0DgnJzhQADAQAAiXNlY3AyNTZrMaECc8NfmEvT4RHt5z0JDwDS2D-4PkZ2n2TeZaqfc_G2bQeDdGNwggeog3VkcIIHqoV3YWt1MgE"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.141.108
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['13197', '13198', '13199', '13200', '13201']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 13197:13197 -p 13198:13198 -p 13199:13199 -p 13200:13200 -p 13201:13201 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=13199 --rest-port=13197 --tcp-port=13198 --discv5-udp-port=13200 --rest-address=0.0.0.0 --nat=extip:172.18.141.108 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=bbfa5f7f252a08c2e9a5cde7715fea4cfac6a44afdd2de1aaf0bff43cc0bdef2 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=13201 --metrics-logging=true --relay=true --discv5-bootstrap-node=enr:-L24QGUYKNfynrtq0MrjvP8jx-nYiofUHeQNybiraV5o9aMyeQPFnUPuh4pwKBzL8a0k8DK6HwXeGrSWutXd-0tO9_sCgmlkgnY0gmlwhKwSNcmKbXVsdGlhZGRyc5YACASsEjXJBgeoAAoErBI1yQYHqd0DgnJzhQADAQAAiXNlY3AyNTZrMaECc8NfmEvT4RHt5z0JDwDS2D-4PkZ2n2TeZaqfc_G2bQeDdGNwggeog3VkcIIHqoV3YWt1MgE
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.141.108 waku c9e47596c6b2c0534fa624cf7311e74d277df8a4509e8165ac5920079bf5546d
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID c9e47596c6b2. Setting up logs at ./log/docker/node2_2024-12-25_19-37-31__bdaa7c46-9caa-43de-be23-70ba1fe3d16e__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 13197
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:13197/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:13197/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.141.108/tcp/13198/p2p/16Uiu2HAmJ4RDSCt6cfoBjEgkNS58bwgF3Pqk5w2JvzBq3PHhNHyX","/ip4/172.18.141.108/tcp/13199/ws/p2p/16Uiu2HAmJ4RDSCt6cfoBjEgkNS58bwgF3Pqk5w2JvzBq3PHhNHyX"],"enrUri":"enr:-L24QHjKLO2pHRfckpLzlCTCUHfXzrhGR7g-b8iqD6MWU-IfMZJTpncuqJHtjqDyDqatfEvr1LFWYTBu4USS1rX69n8CgmlkgnY0gmlwhKwSjWyKbXVsdGlhZGRyc5YACASsEo1sBjOOAAoErBKNbAYzj90DgnJzhQADAQAAiXNlY3AyNTZrMaEDUEroX49Ev1Iy-64KExZp0F2I48XBn-GQEFBOdVrIV1aDdGNwgjOOg3VkcIIzkIV3YWt1MgE"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.145.182
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['42827', '42828', '42829', '42830', '42831']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 42827:42827 -p 42828:42828 -p 42829:42829 -p 42830:42830 -p 42831:42831 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=42829 --rest-port=42827 --tcp-port=42828 --discv5-udp-port=42830 --rest-address=0.0.0.0 --nat=extip:172.18.145.182 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=5f11d2b630acf3971c4e4d898213c65a4bd3b3cba671c7ed7abb2fa270f95dbb --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=42831 --metrics-logging=true --relay=true --discv5-bootstrap-node=enr:-L24QHjKLO2pHRfckpLzlCTCUHfXzrhGR7g-b8iqD6MWU-IfMZJTpncuqJHtjqDyDqatfEvr1LFWYTBu4USS1rX69n8CgmlkgnY0gmlwhKwSjWyKbXVsdGlhZGRyc5YACASsEo1sBjOOAAoErBKNbAYzj90DgnJzhQADAQAAiXNlY3AyNTZrMaEDUEroX49Ev1Iy-64KExZp0F2I48XBn-GQEFBOdVrIV1aDdGNwgjOOg3VkcIIzkIV3YWt1MgE
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.145.182 waku c700d61a5fe7513a9e941fd34d91b60cc4fd3d06bb2bc6cfd74f07c334ca8f0a
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID c700d61a5fe7. Setting up logs at ./log/docker/node3_2024-12-25_19-37-31__bdaa7c46-9caa-43de-be23-70ba1fe3d16e__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 42827
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:42827/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:42827/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.145.182/tcp/42828/p2p/16Uiu2HAmQNLTYJmQQJfP3m8CbeG2vCJJ9tT1i11bm4CiLJXz5aoY","/ip4/172.18.145.182/tcp/42829/ws/p2p/16Uiu2HAmQNLTYJmQQJfP3m8CbeG2vCJJ9tT1i11bm4CiLJXz5aoY"],"enrUri":"enr:-L24QE7djOK20kcpHvup75_OQiqx_fsHQR_HZgHn4v13CjR6feR0Cq3LhdsTktS5NcZe7s5sBRkqs8yWq5o5hOSe25ICgmlkgnY0gmlwhKwSkbaKbXVsdGlhZGRyc5YACASsEpG2BqdMAAoErBKRtganTd0DgnJzhQADAQAAiXNlY3AyNTZrMaEDrgga9FcdC-db03KWtxpWd7-7WlRnGJIggWXMYWfHGt-DdGNwgqdMg3VkcIKnToV3YWt1MgE"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:1959/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:13197/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:42827/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:1959/admin/v1/peers" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"multiaddr":"/ip4/172.18.141.108/tcp/13198/p2p/16Uiu2HAmJ4RDSCt6cfoBjEgkNS58bwgF3Pqk5w2JvzBq3PHhNHyX","protocols":[{"protocol":"/vac/waku/relay/2.0.0","connected":true},{"protocol":"/vac/waku/peer-exchange/2.0.0-alpha1","connected":true}],"origin":"UnknownOrigin"}]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:13197/admin/v1/peers" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"multiaddr":"/ip4/172.18.53.201/tcp/1960/p2p/16Uiu2HAm3DZeuwUC1DnrDAgW7qdpzL7h9Ug9P8m5fN2U5L7ULAjQ","protocols":[{"protocol":"/vac/waku/relay/2.0.0","connected":true},{"protocol":"/vac/waku/peer-exchange/2.0.0-alpha1","connected":true}],"origin":"Discv5"},{"multiaddr":"/ip4/172.18.145.182/tcp/42828/p2p/16Uiu2HAmQNLTYJmQQJfP3m8CbeG2vCJJ9tT1i11bm4CiLJXz5aoY","protocols":[{"protocol":"/vac/waku/relay/2.0.0","connected":true},{"protocol":"/vac/waku/peer-exchange/2.0.0-alpha1","connected":true}],"origin":"UnknownOrigin"}]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:42827/admin/v1/peers" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"multiaddr":"/ip4/172.18.141.108/tcp/13198/p2p/16Uiu2HAmJ4RDSCt6cfoBjEgkNS58bwgF3Pqk5w2JvzBq3PHhNHyX","protocols":[{"protocol":"/vac/waku/relay/2.0.0","connected":true},{"protocol":"/vac/waku/peer-exchange/2.0.0-alpha1","connected":true}],"origin":"Discv5"}]'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 30 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:1959/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d '{"payload": "RmlsdGVyIHdvcmtzISE=", "contentTopic": "/test/1/waku-filter/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[35mDEBUG   [0m src.steps.relay:relay.py:123 Checking that peer NODE_1:wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:42827/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"RmlsdGVyIHdvcmtzISE=","contentTopic":"/test/1/waku-filter/proto","version":0,"timestamp":1735155487990027520,"ephemeral":false}]'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 167f7bb33550
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id c9e47596c6b2
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 167f7bb33550. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id c700d61a5fe7
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container c9e47596c6b2. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.