[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_main_node_only_relay__peer_only_store with id: 2024-06-16_04-27-01__97c24fc5-c2cf-4caf-b1df-6c417c162fc7
[35mDEBUG   [0m src.steps.common:common.py:17 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.store:store.py:27 Running fixture setup: store_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/publishing_node1_2024-06-16_04-27-01__97c24fc5-c2cf-4caf-b1df-6c417c162fc7__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.234.254
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['60515', '60516', '60517', '60518', '60519']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:373 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:120 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 60515:60515 -p 60516:60516 -p 60517:60517 -p 60518:60518 -p 60519:60519 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=60517 --rest-port=60515 --tcp-port=60516 --discv5-udp-port=60518 --rest-address=0.0.0.0 --nat=extip:172.18.234.254 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=60519 --metrics-logging=true --store=false --relay=true --nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.234.254 waku 8de71628f99993f390258f50c5f791ea0bdc68da5049257bef03b80d0f40e417
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 8de71628f999. Setting up logs at ./log/docker/publishing_node1_2024-06-16_04-27-01__97c24fc5-c2cf-4caf-b1df-6c417c162fc7__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:134 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 60515
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:60515/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:225 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:60515/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.234.254/tcp/60516/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.234.254/tcp/60517/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-LO4QMBuTSwWiKPjPNndNd2ksppkx_AFdS9HVT2yheLEg4a3auRNeSGaQtSoO3RPuV_cRg684zbQFSq5kHIrEQdKM6ABgmlkgnY0gmlwhKwS6v6KbXVsdGlhZGRyc4wACgSsEur-Buxl3QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC7GSDdWRwguxmhXdha3UyAQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:230 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/store_node1_2024-06-16_04-27-01__97c24fc5-c2cf-4caf-b1df-6c417c162fc7__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.77.32
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['29989', '29990', '29991', '29992', '29993']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:373 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:120 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 29989:29989 -p 29990:29990 -p 29991:29991 -p 29992:29992 -p 29993:29993 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=29991 --rest-port=29989 --tcp-port=29990 --discv5-udp-port=29992 --rest-address=0.0.0.0 --nat=extip:172.18.77.32 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=29993 --metrics-logging=true --discv5-bootstrap-node=enr:-LO4QMBuTSwWiKPjPNndNd2ksppkx_AFdS9HVT2yheLEg4a3auRNeSGaQtSoO3RPuV_cRg684zbQFSq5kHIrEQdKM6ABgmlkgnY0gmlwhKwS6v6KbXVsdGlhZGRyc4wACgSsEur-Buxl3QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC7GSDdWRwguxmhXdha3UyAQ --storenode=/ip4/172.18.234.254/tcp/60516/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip --store=true --relay=false
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.77.32 waku 1d26ec8160a0bfbbf7a6da82c151049123128435d03f6f359994c32231441b4a
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 1d26ec8160a0. Setting up logs at ./log/docker/store_node1_2024-06-16_04-27-01__97c24fc5-c2cf-4caf-b1df-6c417c162fc7__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:134 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 29989
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:29989/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:225 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:29989/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.77.32/tcp/29990/p2p/16Uiu2HAmQkGr8brtKA9kUciUbJ3Dx8636A49WgdrKQiqGSAhtKvf","/ip4/172.18.77.32/tcp/29991/ws/p2p/16Uiu2HAmQkGr8brtKA9kUciUbJ3Dx8636A49WgdrKQiqGSAhtKvf"],"enrUri":"enr:-LO4QKP7CjTHQqHI6Q_6eH-_hjrQ8bVZ3juEP9oV9JHrXKOqPCzFcnCURKDImIbr8TL5sk7FoKI8JLBt8uXaeU1Q4OQBgmlkgnY0gmlwhKwSTSCKbXVsdGlhZGRyc4wACgSsEk0gBnUn3QOCcnOFAAABAACJc2VjcDI1NmsxoQOzpsz6EZz8Pvurm_1LQl5hV7NdTFdvegI_OOn7yymLiIN0Y3CCdSaDdWRwgnUohXdha3UyAg"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:230 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:29989/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.234.254/tcp/60516/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:60515/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/0/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.store:store.py:127 Relaying message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:60515/relay/v1/messages/%2Fwaku%2F2%2Frs%2F0%2F0" -H "Content-Type: application/json" -d '{"payload": "U3RvcmUgd29ya3MhIQ==", "contentTopic": "/myapp/1/latest/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.01 seconds
[35mDEBUG   [0m src.steps.store:store.py:209 Checking that peer harbor.status.im/wakuorg/nwaku:latest can find the stored message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:29989/store/v3/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F0%2F0&pageSize=5&ascending=true&pubsubTopic=%2Fwaku%2F2%2Frs%2F0%2F0" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"","statusCode":200,"statusDesc":"OK","messages":[]}'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:181 Stopping container with id 8de71628f999
[35mDEBUG   [0m src.node.waku_node:waku_node.py:188 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:181 Stopping container with id 1d26ec8160a0
[35mDEBUG   [0m src.node.waku_node:waku_node.py:188 Container stopped.