[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_get_store_message_with_meta with id: 2024-06-01_04-24-41__e20c7dba-bc28-448a-a270-80347e167e97
[35mDEBUG   [0m src.steps.common:common.py:17 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.store:store.py:27 Running fixture setup: store_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/publishing_node1_2024-06-01_04-24-41__e20c7dba-bc28-448a-a270-80347e167e97__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.56.168
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['35367', '35368', '35369', '35370', '35371']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:373 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:120 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 35367:35367 -p 35368:35368 -p 35369:35369 -p 35370:35370 -p 35371:35371 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=35369 --rest-port=35367 --tcp-port=35368 --discv5-udp-port=35370 --rest-address=0.0.0.0 --nat=extip:172.18.56.168 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=35371 --metrics-logging=true --store=true --relay=true --nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.56.168 waku 41b0def2773656eacb868413ece27806368edaedcf9ed8e720d1c0d1283f961b
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 41b0def27736. Setting up logs at ./log/docker/publishing_node1_2024-06-01_04-24-41__e20c7dba-bc28-448a-a270-80347e167e97__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:134 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 35367
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:35367/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:225 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:35367/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.56.168/tcp/35368/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.56.168/tcp/35369/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-LO4QDoeNxcVDW8C_IpnyG0V9f0mnEmph2A-D2I9Sy-HW0DFId3l6_1wd_SPph3uT8wdV3xQihUppc4PCq4pbM9ktiMBgmlkgnY0gmlwhKwSOKiKbXVsdGlhZGRyc4wACgSsEjioBoop3QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCiiiDdWRwgooqhXdha3UyAw"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:230 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/store_node1_2024-06-01_04-24-41__e20c7dba-bc28-448a-a270-80347e167e97__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.187.143
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['40308', '40309', '40310', '40311', '40312']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:373 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:120 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 40308:40308 -p 40309:40309 -p 40310:40310 -p 40311:40311 -p 40312:40312 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=40310 --rest-port=40308 --tcp-port=40309 --discv5-udp-port=40311 --rest-address=0.0.0.0 --nat=extip:172.18.187.143 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=40312 --metrics-logging=true --discv5-bootstrap-node=enr:-LO4QDoeNxcVDW8C_IpnyG0V9f0mnEmph2A-D2I9Sy-HW0DFId3l6_1wd_SPph3uT8wdV3xQihUppc4PCq4pbM9ktiMBgmlkgnY0gmlwhKwSOKiKbXVsdGlhZGRyc4wACgSsEjioBoop3QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCiiiDdWRwgooqhXdha3UyAw --storenode=/ip4/172.18.56.168/tcp/35368/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip --store=true --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.187.143 waku 423711e9257799d01e637b32dbac05364ef2df577d51d1e751672d11e0f7086c
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 423711e92577. Setting up logs at ./log/docker/store_node1_2024-06-01_04-24-41__e20c7dba-bc28-448a-a270-80347e167e97__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:134 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 40308
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:40308/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:225 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:40308/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.187.143/tcp/40309/p2p/16Uiu2HAkvGErSjcJSznexYjMvK6B5EdmQKt8fPWtif4SkCQiwzLQ","/ip4/172.18.187.143/tcp/40310/ws/p2p/16Uiu2HAkvGErSjcJSznexYjMvK6B5EdmQKt8fPWtif4SkCQiwzLQ"],"enrUri":"enr:-LO4QCBIEbNDBBTnSmqWH4XfE44Dx2kf7DvO3W9Ms4OUG3xhQvuaiuGMu8kHzxWIeGKd-hpt_iwLX8SXSYpMbibTr3gBgmlkgnY0gmlwhKwSu4-KbXVsdGlhZGRyc4wACgSsEruPBp123QOCcnOFAAABAACJc2VjcDI1NmsxoQIMcQx9R4fHZkNr3I4QEfkH5aBAX-YFpoyE0qHj5pk-CYN0Y3CCnXWDdWRwgp13hXdha3UyAw"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:230 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:40308/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.56.168/tcp/35368/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:35367/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/0/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:40308/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/0/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.store:store.py:127 Relaying message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:35367/relay/v1/messages/%2Fwaku%2F2%2Frs%2F0%2F0" -H "Content-Type: application/json" -d '{"payload": "U3RvcmUgd29ya3MhIQ==", "contentTopic": "/myapp/1/latest/proto", "timestamp": '$(date +%s%N)', "meta": "U3RvcmUgd29ya3MhIQ=="}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.01 seconds
[35mDEBUG   [0m src.steps.store:store.py:209 Checking that peer harbor.status.im/wakuorg/nwaku:latest can find the stored message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:35367/store/v3/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F0%2F0&pageSize=5&ascending=true" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"","statusCode":200,"statusDesc":"OK","messages":[{"messageHash":"UY60WwmH4MT9EdYvITUZV7XYYc0/MtDDIAu1kdzmlYk="}]}'
[35mDEBUG   [0m src.steps.store:store.py:209 Checking that peer harbor.status.im/wakuorg/nwaku:latest can find the stored message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:40308/store/v3/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F0%2F0&pageSize=5&ascending=true" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"","statusCode":200,"statusDesc":"OK","messages":[{"messageHash":"UY60WwmH4MT9EdYvITUZV7XYYc0/MtDDIAu1kdzmlYk="}]}'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:181 Stopping container with id 41b0def27736
[35mDEBUG   [0m src.node.waku_node:waku_node.py:188 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:181 Stopping container with id 423711e92577
[35mDEBUG   [0m src.node.waku_node:waku_node.py:188 Container stopped.