[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_message_with_ephemeral_false with id: 2024-06-21_04-26-40__94129683-c95f-48b0-9e00-8b6937545fb0
[35mDEBUG   [0m src.steps.common:common.py:17 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.store:store.py:27 Running fixture setup: store_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/publishing_node1_2024-06-21_04-26-40__94129683-c95f-48b0-9e00-8b6937545fb0__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.132.134
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['56396', '56397', '56398', '56399', '56400']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:373 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:120 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 56396:56396 -p 56397:56397 -p 56398:56398 -p 56399:56399 -p 56400:56400 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=56398 --rest-port=56396 --tcp-port=56397 --discv5-udp-port=56399 --rest-address=0.0.0.0 --nat=extip:172.18.132.134 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=56400 --metrics-logging=true --store=true --relay=true --nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.132.134 waku b7253d3080c76a1b7a6df11159df689d596088804e76a1c6851beedc729e30f4
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID b7253d3080c7. Setting up logs at ./log/docker/publishing_node1_2024-06-21_04-26-40__94129683-c95f-48b0-9e00-8b6937545fb0__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:134 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 56396
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:56396/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:225 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:56396/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.132.134/tcp/56397/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.132.134/tcp/56398/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-LO4QBGTwgADTwGg4CAqOpobcO2Q5Xog8kmgEeXawdpdgk4ZVQZKgl_KoBm2p0MKf5v8xHaMiuKsbMYx9c2ENlW5nzgBgmlkgnY0gmlwhKwShIaKbXVsdGlhZGRyc4wACgSsEoSGBtxO3QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC3E2DdWRwgtxPhXdha3UyAw"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:230 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/store_node1_2024-06-21_04-26-40__94129683-c95f-48b0-9e00-8b6937545fb0__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.85.102
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['54816', '54817', '54818', '54819', '54820']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:373 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:120 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 54816:54816 -p 54817:54817 -p 54818:54818 -p 54819:54819 -p 54820:54820 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=54818 --rest-port=54816 --tcp-port=54817 --discv5-udp-port=54819 --rest-address=0.0.0.0 --nat=extip:172.18.85.102 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=54820 --metrics-logging=true --discv5-bootstrap-node=enr:-LO4QBGTwgADTwGg4CAqOpobcO2Q5Xog8kmgEeXawdpdgk4ZVQZKgl_KoBm2p0MKf5v8xHaMiuKsbMYx9c2ENlW5nzgBgmlkgnY0gmlwhKwShIaKbXVsdGlhZGRyc4wACgSsEoSGBtxO3QOCcnOFAAABAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC3E2DdWRwgtxPhXdha3UyAw --storenode=/ip4/172.18.132.134/tcp/56397/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip --store=true --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.85.102 waku a50bcf8ef06cbf0e9a167957d626163788415b9de68ef1fc120806726d34d311
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID a50bcf8ef06c. Setting up logs at ./log/docker/store_node1_2024-06-21_04-26-40__94129683-c95f-48b0-9e00-8b6937545fb0__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:134 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 54816
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:54816/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:225 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:54816/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.85.102/tcp/54817/p2p/16Uiu2HAkx2BSXZVhsR97pccdw81sqdfrRD2EJxcG3RHB38DdKCaP","/ip4/172.18.85.102/tcp/54818/ws/p2p/16Uiu2HAkx2BSXZVhsR97pccdw81sqdfrRD2EJxcG3RHB38DdKCaP"],"enrUri":"enr:-LO4QNbc-0zwArxWbROCvogEf7dgZqblgtywZjR-BYrKySDoARygHc5Uadvy-vQdsGjrDvMtTNcDow_HnDBbLa1ufU0BgmlkgnY0gmlwhKwSVWaKbXVsdGlhZGRyc4wACgSsElVmBtYi3QOCcnOFAAABAACJc2VjcDI1NmsxoQImjm7Vje5FOWgRWQZW6cdF3K24Yz9TEwuKgPREAlkTbIN0Y3CC1iGDdWRwgtYjhXdha3UyAw"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:230 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:54816/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.132.134/tcp/56397/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:56396/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/0/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:54816/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/0/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.store:store.py:127 Relaying message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:56396/relay/v1/messages/%2Fwaku%2F2%2Frs%2F0%2F0" -H "Content-Type: application/json" -d '{"payload": "U3RvcmUgd29ya3MhIQ==", "contentTopic": "/myapp/1/latest/proto", "timestamp": '$(date +%s%N)', "ephemeral": false}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.01 seconds
[35mDEBUG   [0m src.steps.store:store.py:209 Checking that peer harbor.status.im/wakuorg/nwaku:latest can find the stored message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:56396/store/v3/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F0%2F0&pageSize=5&ascending=true" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"","statusCode":200,"statusDesc":"OK","messages":[{"messageHash":"RGY0ovyLOcCjVrarQIWH5aKLn1GPML0Mhrrb5Y+HYUs="}]}'
[35mDEBUG   [0m src.steps.store:store.py:209 Checking that peer harbor.status.im/wakuorg/nwaku:latest can find the stored message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:54816/store/v3/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F0%2F0&pageSize=5&ascending=true" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"","statusCode":200,"statusDesc":"OK","messages":[{"messageHash":"RGY0ovyLOcCjVrarQIWH5aKLn1GPML0Mhrrb5Y+HYUs="}]}'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:181 Stopping container with id b7253d3080c7
[35mDEBUG   [0m src.node.waku_node:waku_node.py:188 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:181 Stopping container with id a50bcf8ef06c
[35mDEBUG   [0m src.node.waku_node:waku_node.py:188 Container stopped.