[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_2_lightpush_nodes_and_2_receiving_nodes with id: 2025-01-05_19-33-53__e6b8852b-6517-4887-b475-3d57d4d1986b
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.light_push:light_push.py:28 Running fixture setup: light_push_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/receiving_node1_2025-01-05_19-33-53__e6b8852b-6517-4887-b475-3d57d4d1986b__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.1.146
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['58764', '58765', '58766', '58767', '58768']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 58764:58764 -p 58765:58765 -p 58766:58766 -p 58767:58767 -p 58768:58768 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=58766 --rest-port=58764 --tcp-port=58765 --discv5-udp-port=58767 --rest-address=0.0.0.0 --nat=extip:172.18.1.146 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=bf05bbabb39ae3a5fecca8e7adb62cd5c9be9feaf05cdda59c5d1a6f7951a168 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=58768 --metrics-logging=true --lightpush=true --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.1.146 waku f3c849b728f97625b40a5b0d5d735ee217ebfb89fb7cba1b2711154841e47088
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID f3c849b728f9. Setting up logs at ./log/docker/receiving_node1_2025-01-05_19-33-53__e6b8852b-6517-4887-b475-3d57d4d1986b__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 58764
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 60ca0c3c84f2. Exiting log stream.
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 9403c01295a4. Exiting log stream.
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:58764/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:58764/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.1.146/tcp/58765/p2p/16Uiu2HAmLmHUFkeerUnU29aJxFokX9odtay5fyfBeAs59SoMoamQ","/ip4/172.18.1.146/tcp/58766/ws/p2p/16Uiu2HAmLmHUFkeerUnU29aJxFokX9odtay5fyfBeAs59SoMoamQ"],"enrUri":"enr:-L24QB-v4vQi3q4yI9gseIre7mgWQdrZ_fIxzBUncn63LmDtMZpx37-i4gi0PuaEux5nX0i5TGqSp52V-ZfyIF0aBVkCgmlkgnY0gmlwhKwSAZKKbXVsdGlhZGRyc5YACASsEgGSBuWNAAoErBIBkgbljt0DgnJzhQADAQAAiXNlY3AyNTZrMaEDeHpWiBlkpQOiuYQUN-4FLO1UwAU6eLRhoMl9SPFgKyODdGNwguWNg3VkcILlj4V3YWt1Mgk"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/receiving_node2_2025-01-05_19-33-53__e6b8852b-6517-4887-b475-3d57d4d1986b__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.33.57
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['26106', '26107', '26108', '26109', '26110']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 26106:26106 -p 26107:26107 -p 26108:26108 -p 26109:26109 -p 26110:26110 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=26108 --rest-port=26106 --tcp-port=26107 --discv5-udp-port=26109 --rest-address=0.0.0.0 --nat=extip:172.18.33.57 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=becf8a9add92abc6d4bfdca9c5de9075f5d7df05f001cae2c09dfb2e318fbd23 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=26110 --metrics-logging=true --lightpush=false --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.33.57 waku 4cc56055aaf1b67b22949bbb2e26f381943dedc83f7a616ed7e9ecba44418e8c
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 4cc56055aaf1. Setting up logs at ./log/docker/receiving_node2_2025-01-05_19-33-53__e6b8852b-6517-4887-b475-3d57d4d1986b__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 26106
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:26106/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:26106/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.33.57/tcp/26107/p2p/16Uiu2HAm1cHdHbFnMhdLYqPJiVR2WBRugDnhGYH1BcPfv2pF8h7C","/ip4/172.18.33.57/tcp/26108/ws/p2p/16Uiu2HAm1cHdHbFnMhdLYqPJiVR2WBRugDnhGYH1BcPfv2pF8h7C"],"enrUri":"enr:-L24QGNTLEu2zeKTlfJSiBEf6iA-GYhJdmJKDo_B5Hy_rpjYChOEPudB2fdyhEcK23iNiZj1Z_ywzHOfhaAPFK5Wy54CgmlkgnY0gmlwhKwSITmKbXVsdGlhZGRyc5YACASsEiE5BmX7AAoErBIhOQZl_N0DgnJzhQADAQAAiXNlY3AyNTZrMaECW948Nk5OfFjAhRJt-lFt9cSwd_6ZCcVAurKIZpblRh-DdGNwgmX7g3VkcIJl_YV3YWt1MgE"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:26106/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.1.146/tcp/58765/p2p/16Uiu2HAmLmHUFkeerUnU29aJxFokX9odtay5fyfBeAs59SoMoamQ"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/lightpush_node1_2025-01-05_19-33-53__e6b8852b-6517-4887-b475-3d57d4d1986b__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.213.255
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['51343', '51344', '51345', '51346', '51347']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 51343:51343 -p 51344:51344 -p 51345:51345 -p 51346:51346 -p 51347:51347 wakuorg/go-waku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=DEBUG --rest-relay-cache-capacity=100 --websocket-port=51345 --rest-port=51343 --tcp-port=51344 --discv5-udp-port=51346 --rest-address=0.0.0.0 --nat=extip:172.18.213.255 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=4af6beef696adeda6e55046fc15e0ccd613ad61ad7c1c53bee32c8c5a17e9ea9 --min-relay-peers-to-publish=1 --rest-filter-cache-capacity=50 --peer-store-capacity=10 --discv5-bootstrap-node=enr:-L24QB-v4vQi3q4yI9gseIre7mgWQdrZ_fIxzBUncn63LmDtMZpx37-i4gi0PuaEux5nX0i5TGqSp52V-ZfyIF0aBVkCgmlkgnY0gmlwhKwSAZKKbXVsdGlhZGRyc5YACASsEgGSBuWNAAoErBIBkgbljt0DgnJzhQADAQAAiXNlY3AyNTZrMaEDeHpWiBlkpQOiuYQUN-4FLO1UwAU6eLRhoMl9SPFgKyODdGNwguWNg3VkcILlj4V3YWt1Mgk --lightpushnode=/ip4/172.18.1.146/tcp/58765/p2p/16Uiu2HAmLmHUFkeerUnU29aJxFokX9odtay5fyfBeAs59SoMoamQ --lightpush=true --relay=false --pubsub-topic=/waku/2/rs/3/1
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.213.255 waku 435eb8d67dc8e7ec0043adb253fb59f5d377b338e9b046fac69e33d437b83f7a
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 435eb8d67dc8. Setting up logs at ./log/docker/lightpush_node1_2025-01-05_19-33-53__e6b8852b-6517-4887-b475-3d57d4d1986b__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/go-waku:latest. REST: 51343
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:51343/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-KG4QO5HQLP7ExAR_p6Fsdk0-04RpK_5zRNcYIvOmkp4zh0CduIy84sXlQMMf7Ox_8Lqdd0MWv_Fnkp_nzOTfgPh0-WGAZQ39bDJgmlkgnY0gmlwhKwRAASCcnOFAAMBAAGJc2VjcDI1NmsxoQJqBJWevgpKgGUTVyrpyYyrbOq89hLsQHQOfFaBhyTID4N0Y3CCyJCDdWRwgsiShXdha3UyCA","listenAddresses":["/ip4/127.0.0.1/tcp/51344/p2p/16Uiu2HAm2ZXFUrsWzkkiswZmyR3gXMuNX75BnP9iPxTAwPUPR69C","/ip4/127.0.0.1/tcp/51345/ws/p2p/16Uiu2HAm2ZXFUrsWzkkiswZmyR3gXMuNX75BnP9iPxTAwPUPR69C","/ip4/172.17.0.4/tcp/51344/p2p/16Uiu2HAm2ZXFUrsWzkkiswZmyR3gXMuNX75BnP9iPxTAwPUPR69C","/ip4/172.17.0.4/tcp/51345/ws/p2p/16Uiu2HAm2ZXFUrsWzkkiswZmyR3gXMuNX75BnP9iPxTAwPUPR69C"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:51343/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.1.146/tcp/58765/p2p/16Uiu2HAmLmHUFkeerUnU29aJxFokX9odtay5fyfBeAs59SoMoamQ", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:51343/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.33.57/tcp/26107/p2p/16Uiu2HAm1cHdHbFnMhdLYqPJiVR2WBRugDnhGYH1BcPfv2pF8h7C", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/lightpush_node2_2025-01-05_19-33-53__e6b8852b-6517-4887-b475-3d57d4d1986b__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.177.67
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['36837', '36838', '36839', '36840', '36841']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 36837:36837 -p 36838:36838 -p 36839:36839 -p 36840:36840 -p 36841:36841 wakuorg/go-waku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=DEBUG --rest-relay-cache-capacity=100 --websocket-port=36839 --rest-port=36837 --tcp-port=36838 --discv5-udp-port=36840 --rest-address=0.0.0.0 --nat=extip:172.18.177.67 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=bbfda0d69bbb31cfdfb10cec2d9e119152b029c83fbe3b37b9391dbcb8e75720 --min-relay-peers-to-publish=1 --rest-filter-cache-capacity=50 --peer-store-capacity=10 --discv5-bootstrap-node=enr:-L24QB-v4vQi3q4yI9gseIre7mgWQdrZ_fIxzBUncn63LmDtMZpx37-i4gi0PuaEux5nX0i5TGqSp52V-ZfyIF0aBVkCgmlkgnY0gmlwhKwSAZKKbXVsdGlhZGRyc5YACASsEgGSBuWNAAoErBIBkgbljt0DgnJzhQADAQAAiXNlY3AyNTZrMaEDeHpWiBlkpQOiuYQUN-4FLO1UwAU6eLRhoMl9SPFgKyODdGNwguWNg3VkcILlj4V3YWt1Mgk --lightpushnode=/ip4/172.18.1.146/tcp/58765/p2p/16Uiu2HAmLmHUFkeerUnU29aJxFokX9odtay5fyfBeAs59SoMoamQ --lightpush=true --relay=false --pubsub-topic=/waku/2/rs/3/1
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.177.67 waku 62956345df6bdfd5f0d92a80663d73684846544ca47e64b83584d4e6e28c1d9a
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 62956345df6b. Setting up logs at ./log/docker/lightpush_node2_2025-01-05_19-33-53__e6b8852b-6517-4887-b475-3d57d4d1986b__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/go-waku:latest. REST: 36837
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:36837/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-KG4QK9FNyILWtyyvL8Cyirk1nI4_QTsc-EhknaIlD8dSM-XeO7UdSZanSxrpNpR9O5m2i4uceXClVEXeQKoYxy5CNaGAZQ39bXtgmlkgnY0gmlwhKwRAAWCcnOFAAMBAAGJc2VjcDI1NmsxoQMfee6sA0fBg4IKLk7wKhXPVWLguzfZaDSaSds7YgUSPYN0Y3CCj-aDdWRwgo_ohXdha3UyCA","listenAddresses":["/ip4/127.0.0.1/tcp/36838/p2p/16Uiu2HAmEmrpuevrHJtGHh99hHWG5gEXezbp78VT2RkvyMDwxGRz","/ip4/127.0.0.1/tcp/36839/ws/p2p/16Uiu2HAmEmrpuevrHJtGHh99hHWG5gEXezbp78VT2RkvyMDwxGRz","/ip4/172.17.0.5/tcp/36838/p2p/16Uiu2HAmEmrpuevrHJtGHh99hHWG5gEXezbp78VT2RkvyMDwxGRz","/ip4/172.17.0.5/tcp/36839/ws/p2p/16Uiu2HAmEmrpuevrHJtGHh99hHWG5gEXezbp78VT2RkvyMDwxGRz"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:36837/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.1.146/tcp/58765/p2p/16Uiu2HAmLmHUFkeerUnU29aJxFokX9odtay5fyfBeAs59SoMoamQ", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:36837/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.33.57/tcp/26107/p2p/16Uiu2HAm1cHdHbFnMhdLYqPJiVR2WBRugDnhGYH1BcPfv2pF8h7C", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:58764/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:26106/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.light_push:light_push.py:121 Lightpushing message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:51343/lightpush/v1/message" -H "Content-Type: application/json" -d '{"pubsubTopic": "/waku/2/rs/3/0", "message": {"payload": "TGlnaHQgcHVzaCB3b3JrcyEh", "contentTopic": "/myapp/1/latest/proto", "timestamp": 1736105638385301504}}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'true'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.light_push:light_push.py:125 Checking that peer NODE_1:wakuorg/nwaku:latest can find the lightpushed message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:58764/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F0" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"TGlnaHQgcHVzaCB3b3JrcyEh","contentTopic":"/myapp/1/latest/proto","version":0,"timestamp":1736105638385301504,"ephemeral":false}]'
[35mDEBUG   [0m src.steps.light_push:light_push.py:125 Checking that peer NODE_2:wakuorg/nwaku:latest can find the lightpushed message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:26106/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F0" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"TGlnaHQgcHVzaCB3b3JrcyEh","contentTopic":"/myapp/1/latest/proto","version":0,"timestamp":1736105638385301504,"ephemeral":false}]'
[35mDEBUG   [0m src.steps.light_push:light_push.py:121 Lightpushing message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:36837/lightpush/v1/message" -H "Content-Type: application/json" -d '{"pubsubTopic": "/waku/2/rs/3/0", "message": {"payload": "TGlnaHQgcHVzaCB3b3JrcyEh", "contentTopic": "/myapp/1/latest/proto", "timestamp": 1736105638498985472}}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'true'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.light_push:light_push.py:125 Checking that peer NODE_1:wakuorg/nwaku:latest can find the lightpushed message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:58764/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F0" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"TGlnaHQgcHVzaCB3b3JrcyEh","contentTopic":"/myapp/1/latest/proto","version":0,"timestamp":1736105638498985472,"ephemeral":false}]'
[35mDEBUG   [0m src.steps.light_push:light_push.py:125 Checking that peer NODE_2:wakuorg/nwaku:latest can find the lightpushed message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:26106/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F0" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"TGlnaHQgcHVzaCB3b3JrcyEh","contentTopic":"/myapp/1/latest/proto","version":0,"timestamp":1736105638498985472,"ephemeral":false}]'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id f3c849b728f9
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 4cc56055aaf1
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container f3c849b728f9. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 435eb8d67dc8
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 62956345df6b
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 4cc56055aaf1. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.