[35mDEBUG   [0m tests.conftest:conftest.py:43 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:49 Running test: test_auto_shard_relay with id: 2024-05-06_14-12-17__f017618e-7f75-4ca2-a680-22151718b89b
[35mDEBUG   [0m src.steps.common:common.py:15 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.sharding:sharding.py:30 Running fixture setup: sharding_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/node1_2024-05-06_14-12-17__f017618e-7f75-4ca2-a680-22151718b89b__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.16.82
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['62550', '62551', '62552', '62553', '62554']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:327 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:114 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:116 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 62550:62550 -p 62551:62551 -p 62552:62552 -p 62553:62553 -p 62554:62554 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=62552 --rest-port=62550 --tcp-port=62551 --discv5-udp-port=62553 --rest-address=0.0.0.0 --nat=extip:172.18.16.82 --peer-exchange=true --discv5-discovery=true --cluster-id=2 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=62554 --metrics-logging=true --relay=true --filter=true --nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68 --content-topic=/myapp/1/latest/proto
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.16.82 waku ef3b917f0e54a3f51ed9cb902b0e4dff73b1cd040e756a7b56f55316ebf66591
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID ef3b917f0e54. Setting up logs at ./log/docker/node1_2024-05-06_14-12-17__f017618e-7f75-4ca2-a680-22151718b89b__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 62550
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:62550/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.16.82/tcp/62551/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.16.82/tcp/62552/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-LO4QJ0i-uTrBaKhLVagc7eyXAphmAXKxiumsmjYo1gM03wLfsw3FcColFaiLWmTfsSbglmBDUX1FVgwsRFmMlEratEBgmlkgnY0gmlwhKwSEFKKbXVsdGlhZGRyc4wACgSsEhBSBvRY3QOCcnOFAAIBAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC9FeDdWRwgvRZhXdha3UyBQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:193 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/node2_2024-05-06_14-12-17__f017618e-7f75-4ca2-a680-22151718b89b__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.90.183
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['27477', '27478', '27479', '27480', '27481']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:327 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:114 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:116 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 27477:27477 -p 27478:27478 -p 27479:27479 -p 27480:27480 -p 27481:27481 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=27479 --rest-port=27477 --tcp-port=27478 --discv5-udp-port=27480 --rest-address=0.0.0.0 --nat=extip:172.18.90.183 --peer-exchange=true --discv5-discovery=true --cluster-id=2 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=27481 --metrics-logging=true --relay=true --discv5-bootstrap-node=enr:-LO4QJ0i-uTrBaKhLVagc7eyXAphmAXKxiumsmjYo1gM03wLfsw3FcColFaiLWmTfsSbglmBDUX1FVgwsRFmMlEratEBgmlkgnY0gmlwhKwSEFKKbXVsdGlhZGRyc4wACgSsEhBSBvRY3QOCcnOFAAIBAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC9FeDdWRwgvRZhXdha3UyBQ --content-topic=/myapp/1/latest/proto
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.90.183 waku 387161f199d35b90cdd079c5f112030d8be8f23ecc7c506bcfa5803c3b28772b
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 387161f199d3. Setting up logs at ./log/docker/node2_2024-05-06_14-12-17__f017618e-7f75-4ca2-a680-22151718b89b__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 27477
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:27477/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.90.183/tcp/27478/p2p/16Uiu2HAm1TNWjeG2cpEmqdB4XqU99BRH6y5kg31NqVKgFFiGUaZ7","/ip4/172.18.90.183/tcp/27479/ws/p2p/16Uiu2HAm1TNWjeG2cpEmqdB4XqU99BRH6y5kg31NqVKgFFiGUaZ7"],"enrUri":"enr:-LO4QIa6ow6PZIJzBq9a_7aPbSl66SjharkkOXPHEcWcvZh0FzuNTYzVPP_A4Ny-7kw-tfab_lixeAYZAXefSnWou4cBgmlkgnY0gmlwhKwSWreKbXVsdGlhZGRyc4wACgSsElq3BmtX3QOCcnOFAAIBAACJc2VjcDI1NmsxoQJZlYiirWzA2hafre0DQvbt7ILdpkPz0FZsT-8DRdUbMoN0Y3CCa1aDdWRwgmtYhXdha3UyAQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:193 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:27477/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.16.82/tcp/62551/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/node3_2024-05-06_14-12-17__f017618e-7f75-4ca2-a680-22151718b89b__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.90.110
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['7678', '7679', '7680', '7681', '7682']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:327 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:114 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:116 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 7678:7678 -p 7679:7679 -p 7680:7680 -p 7681:7681 -p 7682:7682 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=7680 --rest-port=7678 --tcp-port=7679 --discv5-udp-port=7681 --rest-address=0.0.0.0 --nat=extip:172.18.90.110 --peer-exchange=true --discv5-discovery=true --cluster-id=2 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=7682 --metrics-logging=true --relay=true --discv5-bootstrap-node=enr:-LO4QJ0i-uTrBaKhLVagc7eyXAphmAXKxiumsmjYo1gM03wLfsw3FcColFaiLWmTfsSbglmBDUX1FVgwsRFmMlEratEBgmlkgnY0gmlwhKwSEFKKbXVsdGlhZGRyc4wACgSsEhBSBvRY3QOCcnOFAAIBAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC9FeDdWRwgvRZhXdha3UyBQ --content-topic=/myapp/1/latest/proto
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.90.110 waku c11b8afac1669ff1c2d1ab90f8438ecc040d96fda35c28311fab6d79a73f21bd
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID c11b8afac166. Setting up logs at ./log/docker/node3_2024-05-06_14-12-17__f017618e-7f75-4ca2-a680-22151718b89b__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 7678
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:7678/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.90.110/tcp/7679/p2p/16Uiu2HAmF81oHLksVEUm2nafRtrDvBT79JxVqEypnYK43wQYqqzB","/ip4/172.18.90.110/tcp/7680/ws/p2p/16Uiu2HAmF81oHLksVEUm2nafRtrDvBT79JxVqEypnYK43wQYqqzB"],"enrUri":"enr:-LO4QHhbwo4kAyN0IYzi9mrHI7X7cD8lKuwXbG9UXizys2AYW746o3lWZNg_PVBUgHbBDnEvuQ2iD8KP_xdV9i_OJWUBgmlkgnY0gmlwhKwSWm6KbXVsdGlhZGRyc4wACgSsElpuBh4A3QOCcnOFAAIBAACJc2VjcDI1NmsxoQMko7FwrylGHd-EK_8kdfC7CXzumMuJcsn_pDwVNf8jBIN0Y3CCHf-DdWRwgh4BhXdha3UyAQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:193 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:7678/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.16.82/tcp/62551/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/node4_2024-05-06_14-12-17__f017618e-7f75-4ca2-a680-22151718b89b__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.61.30
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['2899', '2900', '2901', '2902', '2903']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:327 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:114 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:116 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 2899:2899 -p 2900:2900 -p 2901:2901 -p 2902:2902 -p 2903:2903 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=2901 --rest-port=2899 --tcp-port=2900 --discv5-udp-port=2902 --rest-address=0.0.0.0 --nat=extip:172.18.61.30 --peer-exchange=true --discv5-discovery=true --cluster-id=2 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=2903 --metrics-logging=true --relay=true --discv5-bootstrap-node=enr:-LO4QJ0i-uTrBaKhLVagc7eyXAphmAXKxiumsmjYo1gM03wLfsw3FcColFaiLWmTfsSbglmBDUX1FVgwsRFmMlEratEBgmlkgnY0gmlwhKwSEFKKbXVsdGlhZGRyc4wACgSsEhBSBvRY3QOCcnOFAAIBAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC9FeDdWRwgvRZhXdha3UyBQ --content-topic=/myapp/1/latest/proto
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.61.30 waku 29a75d8d5096da0836245f82009c2776524fbbf864fbc7914407154c15963e41
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 29a75d8d5096. Setting up logs at ./log/docker/node4_2024-05-06_14-12-17__f017618e-7f75-4ca2-a680-22151718b89b__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 2899
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:2899/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.61.30/tcp/2900/p2p/16Uiu2HAmRNJRmF5pNSPjPzS3BEZMyGafiRoQiomrDmUqmBZWHLeS","/ip4/172.18.61.30/tcp/2901/ws/p2p/16Uiu2HAmRNJRmF5pNSPjPzS3BEZMyGafiRoQiomrDmUqmBZWHLeS"],"enrUri":"enr:-LO4QL6TrZ4RkoeyVdCbpshk1f0ZikJ_BhxNyLXft4_LD-_wEIivKk49WhuTmZ5653Ma1GYQgEeX5ljLCZuMfQJxvIMBgmlkgnY0gmlwhKwSPR6KbXVsdGlhZGRyc4wACgSsEj0eBgtV3QOCcnOFAAIBAACJc2VjcDI1NmsxoQO84X8E5Htly5qPAhom_OyU7NF1mogMRzvIFQL4ibVt94N0Y3CCC1SDdWRwggtWhXdha3UyAQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:193 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:2899/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.16.82/tcp/62551/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/node5_2024-05-06_14-12-17__f017618e-7f75-4ca2-a680-22151718b89b__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.40.98
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['28287', '28288', '28289', '28290', '28291']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:327 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:114 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:116 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 28287:28287 -p 28288:28288 -p 28289:28289 -p 28290:28290 -p 28291:28291 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=28289 --rest-port=28287 --tcp-port=28288 --discv5-udp-port=28290 --rest-address=0.0.0.0 --nat=extip:172.18.40.98 --peer-exchange=true --discv5-discovery=true --cluster-id=2 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=28291 --metrics-logging=true --relay=true --discv5-bootstrap-node=enr:-LO4QJ0i-uTrBaKhLVagc7eyXAphmAXKxiumsmjYo1gM03wLfsw3FcColFaiLWmTfsSbglmBDUX1FVgwsRFmMlEratEBgmlkgnY0gmlwhKwSEFKKbXVsdGlhZGRyc4wACgSsEhBSBvRY3QOCcnOFAAIBAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CC9FeDdWRwgvRZhXdha3UyBQ --content-topic=/myapp/1/latest/proto
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.40.98 waku 2e15d5b5b6bc3136ea65684ad2f13c46995d7f39a94d782a471cd18a22ae93ac
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 2e15d5b5b6bc. Setting up logs at ./log/docker/node5_2024-05-06_14-12-17__f017618e-7f75-4ca2-a680-22151718b89b__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 28287
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:28287/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.40.98/tcp/28288/p2p/16Uiu2HAmRs2woBj36SEAaavL9tMsr3B5ic1iThH4JwA7rC7pBg6A","/ip4/172.18.40.98/tcp/28289/ws/p2p/16Uiu2HAmRs2woBj36SEAaavL9tMsr3B5ic1iThH4JwA7rC7pBg6A"],"enrUri":"enr:-LO4QLy50qELxK0N6CZOknik-oGWSLGZKeXNkE0j9424J2CCaTMoi-e6UdAmOC_cGAsBkEYCW93BhEvwEHyBEfKosDUBgmlkgnY0gmlwhKwSKGKKbXVsdGlhZGRyc4wACgSsEihiBm6B3QOCcnOFAAIBAACJc2VjcDI1NmsxoQPEPdV4ua2ZzPX2fASOR4y90Ru8oNQWjqR-ZWMZB3CWJ4N0Y3CCboCDdWRwgm6ChXdha3UyAQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:193 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:28287/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.16.82/tcp/62551/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:62550/relay/v1/auto/subscriptions" -H "Content-Type: application/json" -d '["/myapp/1/latest/proto"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:27477/relay/v1/auto/subscriptions" -H "Content-Type: application/json" -d '["/myapp/1/latest/proto"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:7678/relay/v1/auto/subscriptions" -H "Content-Type: application/json" -d '["/myapp/1/latest/proto"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:2899/relay/v1/auto/subscriptions" -H "Content-Type: application/json" -d '["/myapp/1/latest/proto"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:28287/relay/v1/auto/subscriptions" -H "Content-Type: application/json" -d '["/myapp/1/latest/proto"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:62550/relay/v1/auto/messages" -H "Content-Type: application/json" -d '{"payload": "U2hhcmRpbmcgd29ya3MhIQ==", "contentTopic": "/myapp/1/latest/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.sharding:sharding.py:174 Checking that peer NODE_1:harbor.status.im/wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:62550/relay/v1/auto/messages/%2Fmyapp%2F1%2Flatest%2Fproto" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"U2hhcmRpbmcgd29ya3MhIQ==","contentTopic":"/myapp/1/latest/proto","version":0,"timestamp":1715004745337425408,"ephemeral":false}]'
[35mDEBUG   [0m src.steps.sharding:sharding.py:174 Checking that peer NODE_2:harbor.status.im/wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:27477/relay/v1/auto/messages/%2Fmyapp%2F1%2Flatest%2Fproto" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"U2hhcmRpbmcgd29ya3MhIQ==","contentTopic":"/myapp/1/latest/proto","version":0,"timestamp":1715004745337425408,"ephemeral":false}]'
[35mDEBUG   [0m src.steps.sharding:sharding.py:174 Checking that peer NODE_3:harbor.status.im/wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:7678/relay/v1/auto/messages/%2Fmyapp%2F1%2Flatest%2Fproto" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"U2hhcmRpbmcgd29ya3MhIQ==","contentTopic":"/myapp/1/latest/proto","version":0,"timestamp":1715004745337425408,"ephemeral":false}]'
[35mDEBUG   [0m src.steps.sharding:sharding.py:174 Checking that peer NODE_4:harbor.status.im/wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:2899/relay/v1/auto/messages/%2Fmyapp%2F1%2Flatest%2Fproto" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"U2hhcmRpbmcgd29ya3MhIQ==","contentTopic":"/myapp/1/latest/proto","version":0,"timestamp":1715004745337425408,"ephemeral":false}]'
[35mDEBUG   [0m src.steps.sharding:sharding.py:174 Checking that peer NODE_5:harbor.status.im/wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:28287/relay/v1/auto/messages/%2Fmyapp%2F1%2Flatest%2Fproto" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"U2hhcmRpbmcgd29ya3MhIQ==","contentTopic":"/myapp/1/latest/proto","version":0,"timestamp":1715004745337425408,"ephemeral":false}]'
[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:75 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:169 Stopping container with id ef3b917f0e54
[35mDEBUG   [0m src.node.waku_node:waku_node.py:172 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:169 Stopping container with id 387161f199d3
[35mDEBUG   [0m src.node.waku_node:waku_node.py:172 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:169 Stopping container with id c11b8afac166
[35mDEBUG   [0m src.node.waku_node:waku_node.py:172 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:169 Stopping container with id 29a75d8d5096
[35mDEBUG   [0m src.node.waku_node:waku_node.py:172 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:169 Stopping container with id 2e15d5b5b6bc
[35mDEBUG   [0m src.node.waku_node:waku_node.py:172 Container stopped.