[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_metrics_after_store_get with id: 2025-02-14_03-06-32__8d041124-37d1-4585-90e2-746fff0eeaf4
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.light_push:light_push.py:28 Running fixture setup: light_push_setup
[35mDEBUG   [0m src.steps.relay:relay.py:28 Running fixture setup: relay_setup
[35mDEBUG   [0m src.steps.store:store.py:31 Running fixture setup: store_setup
[35mDEBUG   [0m src.steps.store:store.py:39 Running fixture setup: node_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/publishing_node1_2025-02-14_03-06-32__8d041124-37d1-4585-90e2-746fff0eeaf4__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.131.78
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['12553', '12554', '12555', '12556', '12557']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 12553:12553 -p 12554:12554 -p 12555:12555 -p 12556:12556 -p 12557:12557 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=12555 --rest-port=12553 --tcp-port=12554 --discv5-udp-port=12556 --rest-address=0.0.0.0 --nat=extip:172.18.131.78 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=04f4f093c77aaef1076cc5cbbcfd74f8abc5cbebe3be1ed8ffab32778d300cc9 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=12557 --metrics-logging=true --store=true --relay=true
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container db14bafc427b. Exiting log stream.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.131.78 waku d8387c51c1ee2f0d7e2970164bba52d15b2511dd50b5a754bb2b8967075b1862
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID d8387c51c1ee. Setting up logs at ./log/docker/publishing_node1_2025-02-14_03-06-32__8d041124-37d1-4585-90e2-746fff0eeaf4__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 12553
[35mDEBUG   [0m src.libs.common:common.py:47 Sleeping for 1 seconds
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 4acfb602bf33. Exiting log stream.
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:12553/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:12553/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.131.78/tcp/12554/p2p/16Uiu2HAmPtomisgyke43Y28NHvDLwcezxujTgtzHTKahJhdpE97c","/ip4/172.18.131.78/tcp/12555/ws/p2p/16Uiu2HAmPtomisgyke43Y28NHvDLwcezxujTgtzHTKahJhdpE97c"],"enrUri":"enr:-L24QClsACU2peZffJaSSGmJ-NgJZ6dmVk2TvQmAg_YSg68NG5hfZicqNSnXeMuvqwHwh4l6anSGoG9JupjXubagkZsCgmlkgnY0gmlwhKwSg06KbXVsdGlhZGRyc5YACASsEoNOBjEKAAoErBKDTgYxC90DgnJzhQADAQAAiXNlY3AyNTZrMaEDpvq54Uz2LQSls8hdafP2htTrMS7qAb2GMS5mxUHEFZeDdGNwgjEKg3VkcIIxDIV3YWt1MgM"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/store_node1_2025-02-14_03-06-32__8d041124-37d1-4585-90e2-746fff0eeaf4__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.71.25
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['23404', '23405', '23406', '23407', '23408']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 23404:23404 -p 23405:23405 -p 23406:23406 -p 23407:23407 -p 23408:23408 wakuorg/go-waku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=DEBUG --rest-relay-cache-capacity=100 --websocket-port=23406 --rest-port=23404 --tcp-port=23405 --discv5-udp-port=23407 --rest-address=0.0.0.0 --nat=extip:172.18.71.25 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=ed3edcf2c8dffcebe08b5bc1398a7ef5aed23cdff0d6fd28df4cebdd5a9a9f6d --min-relay-peers-to-publish=1 --rest-filter-cache-capacity=50 --peer-store-capacity=10 --discv5-bootstrap-node=enr:-L24QClsACU2peZffJaSSGmJ-NgJZ6dmVk2TvQmAg_YSg68NG5hfZicqNSnXeMuvqwHwh4l6anSGoG9JupjXubagkZsCgmlkgnY0gmlwhKwSg06KbXVsdGlhZGRyc5YACASsEoNOBjEKAAoErBKDTgYxC90DgnJzhQADAQAAiXNlY3AyNTZrMaEDpvq54Uz2LQSls8hdafP2htTrMS7qAb2GMS5mxUHEFZeDdGNwgjEKg3VkcIIxDIV3YWt1MgM --storenode=/ip4/172.18.131.78/tcp/12554/p2p/16Uiu2HAmPtomisgyke43Y28NHvDLwcezxujTgtzHTKahJhdpE97c --store=true --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.71.25 waku dabde496e3f8593701c3e549f9af7d87d0c3da9aaf87fcee6d70dd10f770df6c
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID dabde496e3f8. Setting up logs at ./log/docker/store_node1_2025-02-14_03-06-32__8d041124-37d1-4585-90e2-746fff0eeaf4__wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/go-waku:latest. REST: 23404
[35mDEBUG   [0m src.libs.common:common.py:47 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:23404/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-J-4QAdihDsk5fX6qEtN7FVF2gk0P9QgkLnn3MG2KT3IROpjVsBz1XqvNcRFXBRPim1NJlec3xftUmcfuNpLboDbmUyGAZUCbBpugmlkgnY0gmlwhKwRAAOCcnODAAMAiXNlY3AyNTZrMaED1iFt9BSK6jySE1M6ACyynnpGSt4V_1S7qswU-VUcHcuDdGNwglttg3VkcIJbb4V3YWt1MgM","listenAddresses":["/ip4/127.0.0.1/tcp/23405/p2p/16Uiu2HAmT4sARAhsTF9Tk1xfFqSzx7SePs1cqZFG8PiA519sAi3C","/ip4/127.0.0.1/tcp/23406/ws/p2p/16Uiu2HAmT4sARAhsTF9Tk1xfFqSzx7SePs1cqZFG8PiA519sAi3C","/ip4/172.17.0.3/tcp/23405/p2p/16Uiu2HAmT4sARAhsTF9Tk1xfFqSzx7SePs1cqZFG8PiA519sAi3C","/ip4/172.17.0.3/tcp/23406/ws/p2p/16Uiu2HAmT4sARAhsTF9Tk1xfFqSzx7SePs1cqZFG8PiA519sAi3C"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:23404/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.131.78/tcp/12554/p2p/16Uiu2HAmPtomisgyke43Y28NHvDLwcezxujTgtzHTKahJhdpE97c", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:12553/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:23404/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'true'
[35mDEBUG   [0m src.steps.store:store.py:132 Relaying message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:12553/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d '{"payload": "UmVsYXkgd29ya3MhIQ==", "contentTopic": "/test/1/waku-relay/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:47 Sleeping for 0.2 seconds
[35mDEBUG   [0m src.steps.store:store.py:218 Checking that peer wakuorg/nwaku:latest can find the stored messages
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:12553/store/v3/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F3%2F1&pageSize=50&ascending=true" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"","statusCode":200,"statusDesc":"OK","messages":[{"messageHash":"0x31b3d9782ceaa4296dd7417f37ddaf9040bc2531ecd4b373f7c077f8e1e697d3"}]}'
[35mDEBUG   [0m src.steps.store:store.py:218 Checking that peer wakuorg/go-waku:latest can find the stored messages
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:23404/store/v3/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F3%2F1&contentTopics=%2Ftest%2F1%2Fwaku-relay%2Fproto&pageSize=50&ascending=true" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"request_id":"948ffd6264ea0f629e999680b4e07746bc3f8405cd9d827308e53fb94ecb98ba","status_code":200,"status_desc":"OK","messages":[{"message_hash":"MbPZeCzqpClt10F/N92vkEC8JTHs1LNz98B3+OHml9M="}]}'
[35mDEBUG   [0m src.libs.common:common.py:47 Sleeping for 5 seconds
[35mDEBUG   [0m src.steps.metrics:metrics.py:15 Checking metric: libp2p_peers has 1
[35mDEBUG   [0m src.steps.metrics:metrics.py:27 Found metric: libp2p_peers with value 1.0
[35mDEBUG   [0m src.steps.metrics:metrics.py:15 Checking metric: libp2p_pubsub_peers has 1
[35mDEBUG   [0m src.steps.metrics:metrics.py:27 Found metric: libp2p_pubsub_peers with value 1.0
[35mDEBUG   [0m src.steps.metrics:metrics.py:15 Checking metric: libp2p_pubsub_topics has 1
[35mDEBUG   [0m src.steps.metrics:metrics.py:27 Found metric: libp2p_pubsub_topics with value 2.0
[35mDEBUG   [0m src.steps.metrics:metrics.py:15 Checking metric: libp2p_pubsub_subscriptions_total has 1
[35mDEBUG   [0m src.steps.metrics:metrics.py:27 Found metric: libp2p_pubsub_subscriptions_total with value 2.0
[35mDEBUG   [0m src.steps.metrics:metrics.py:15 Checking metric: waku_peer_store_size has 1
[35mDEBUG   [0m src.steps.metrics:metrics.py:27 Found metric: waku_peer_store_size with value 1.0
[35mDEBUG   [0m src.steps.metrics:metrics.py:15 Checking metric: waku_histogram_message_size_count has 1
[35mDEBUG   [0m src.steps.metrics:metrics.py:27 Found metric: waku_histogram_message_size_count with value 1.0
[35mDEBUG   [0m src.steps.metrics:metrics.py:15 Checking metric: waku_node_messages_total{type="relay"} has 1
[35mDEBUG   [0m src.steps.metrics:metrics.py:27 Found metric: waku_node_messages_total{type="relay"} with value 1.0
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id d8387c51c1ee
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id dabde496e3f8
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.