[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_cant_publish_on_not_subscribed_shard with id: 2024-06-10_04-22-50__60d3abd0-32b5-4e3b-9e0e-07d60bcdf67f
[35mDEBUG   [0m src.steps.common:common.py:17 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.sharding:sharding.py:30 Running fixture setup: sharding_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/node1_2024-06-10_04-22-50__60d3abd0-32b5-4e3b-9e0e-07d60bcdf67f__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.steps.sharding:sharding.py:235 Cluster id was resolved to: 2
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.191.226
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['19530', '19531', '19532', '19533', '19534']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:373 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:120 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 19530:19530 -p 19531:19531 -p 19532:19532 -p 19533:19533 -p 19534:19534 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=19532 --rest-port=19530 --tcp-port=19531 --discv5-udp-port=19533 --rest-address=0.0.0.0 --nat=extip:172.18.191.226 --peer-exchange=true --discv5-discovery=true --cluster-id=2 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=19534 --metrics-logging=true --relay=true --filter=true --nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68 --pubsub-topic=/waku/2/rs/2/0
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.191.226 waku 732800f0646f325bb71486fc3d19e9ff06de3fc5fe2c81157057b2a9944c672d
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 732800f0646f. Setting up logs at ./log/docker/node1_2024-06-10_04-22-50__60d3abd0-32b5-4e3b-9e0e-07d60bcdf67f__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:134 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 19530
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:19530/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:225 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:19530/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.191.226/tcp/19531/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.191.226/tcp/19532/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-LO4QM2EPdZobv7VVtQTMiKFokV6tvpSdGAXIQ6Yrl6Jej84VYu_avi9jtTCS8cTc1lJipL9HsasBXH800d-kXZ7PGUBgmlkgnY0gmlwhKwSv-KKbXVsdGlhZGRyc4wACgSsEr_iBkxM3QOCcnOFAAIBAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCTEuDdWRwgkxNhXdha3UyBQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:230 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/node2_2024-06-10_04-22-50__60d3abd0-32b5-4e3b-9e0e-07d60bcdf67f__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.steps.sharding:sharding.py:235 Cluster id was resolved to: 2
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.157.92
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['2073', '2074', '2075', '2076', '2077']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:373 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:120 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 2073:2073 -p 2074:2074 -p 2075:2075 -p 2076:2076 -p 2077:2077 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=2075 --rest-port=2073 --tcp-port=2074 --discv5-udp-port=2076 --rest-address=0.0.0.0 --nat=extip:172.18.157.92 --peer-exchange=true --discv5-discovery=true --cluster-id=2 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=2077 --metrics-logging=true --relay=true --discv5-bootstrap-node=enr:-LO4QM2EPdZobv7VVtQTMiKFokV6tvpSdGAXIQ6Yrl6Jej84VYu_avi9jtTCS8cTc1lJipL9HsasBXH800d-kXZ7PGUBgmlkgnY0gmlwhKwSv-KKbXVsdGlhZGRyc4wACgSsEr_iBkxM3QOCcnOFAAIBAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCTEuDdWRwgkxNhXdha3UyBQ --pubsub-topic=/waku/2/rs/2/0
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.157.92 waku e27b91ca7f1155b4703ea1fd4fa445a9ee0089ca55b89ff9e3621800ee326946
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID e27b91ca7f11. Setting up logs at ./log/docker/node2_2024-06-10_04-22-50__60d3abd0-32b5-4e3b-9e0e-07d60bcdf67f__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:134 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 2073
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:2073/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:225 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:2073/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.157.92/tcp/2074/p2p/16Uiu2HAm8uLHXcYFjZQanSWKvuWK9uum3Wmh3tdDeX7C8mZuJXRo","/ip4/172.18.157.92/tcp/2075/ws/p2p/16Uiu2HAm8uLHXcYFjZQanSWKvuWK9uum3Wmh3tdDeX7C8mZuJXRo"],"enrUri":"enr:-LO4QEqGsJEXhVtmETXV9BUJd6E-HYlrSJebORLVm3sCEDJEe7SAJi7F3P1VzY3QPtYXBRky2r3vGy1wQmh-ml4XKWMBgmlkgnY0gmlwhKwSnVyKbXVsdGlhZGRyc4wACgSsEp1cBggb3QOCcnOFAAIBAACJc2VjcDI1NmsxoQLIPeyjah7I1TtCX3glj_Ok9B8cyigpRJHTSaX6YdoLPoN0Y3CCCBqDdWRwgggchXdha3UyAQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:230 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:2073/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.191.226/tcp/19531/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:19530/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/2/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:2073/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/2/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:19530/relay/v1/messages/%2Fwaku%2F2%2Frs%2F2%2F1" -H "Content-Type: application/json" -d '{"payload": "U2hhcmRpbmcgd29ya3MhIQ==", "contentTopic": "/myapp/1/latest/proto", "timestamp": '$(date +%s%N)'}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:19530/relay/v1/messages/%2Fwaku%2F2%2Frs%2F2%2F1. Response content: b'Failed to publish: Node not subscribed to topic: /waku/2/rs/2/1'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:181 Stopping container with id 732800f0646f
[35mDEBUG   [0m src.node.waku_node:waku_node.py:188 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:181 Stopping container with id e27b91ca7f11
[35mDEBUG   [0m src.node.waku_node:waku_node.py:188 Container stopped.