[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_valid_payloads_random_user_message_limit with id: 2024-12-11_04-05-16__d94d5ae1-5ff9-401b-95f7-50da32309128
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.relay:relay.py:28 Running fixture setup: relay_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-12-11_04-05-16__d94d5ae1-5ff9-401b-95f7-50da32309128__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.63.147
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['5053', '5054', '5055', '5056', '5057']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes ['/home/runner/work/waku-interop-tests/waku-interop-tests/rln_tree_equg_1:/etc/rln_tree', '/home/runner/work/waku-interop-tests/waku-interop-tests/keystore_equg_1:/keystore']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 5053:5053 -p 5054:5054 -p 5055:5055 -p 5056:5056 -p 5057:5057 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=5055 --rest-port=5053 --tcp-port=5054 --discv5-udp-port=5056 --rest-address=0.0.0.0 --nat=extip:172.18.63.147 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=dbde54bb2b460f0816ed9cda0acdbbb1d0b22cfd1ed263e91c09ce9aaeacbaf4 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=5057 --metrics-logging=true --relay=true --rln-relay-membership-index=1 --rln-relay-user-message-limit=3 --rln-relay-epoch-sec=1 --rln-relay=true --rln-relay-cred-path=/keystore/keystore.json --rln-relay-cred-password=password
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.63.147 waku aac8c52d323fecc89e4d3441efa5d177731fb68170563fb3f96beaf867a94c02
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID aac8c52d323f. Setting up logs at ./log/docker/node1_2024-12-11_04-05-16__d94d5ae1-5ff9-401b-95f7-50da32309128__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 5053
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 0c18cf5e9bbd. Exiting log stream.
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:5053/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Initializing","protocolsHealth":[{"Rln Relay":"Ready"}]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:5053/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[{"Rln Relay":"Ready"}]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:5053/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.63.147/tcp/5054/p2p/16Uiu2HAmE1MLYBpLk7UXCYXfrp6sk1xySh7xGY4LRKKbHvCXbUu3","/ip4/172.18.63.147/tcp/5055/ws/p2p/16Uiu2HAmE1MLYBpLk7UXCYXfrp6sk1xySh7xGY4LRKKbHvCXbUu3"],"enrUri":"enr:-L24QMVtg9LKpBfmGdIgl1_TDUUdV9c8MgkR0iatA7c8WPeUJ03hSNwYqNv44B8xmPSHJE1c4bTiB8YM5rvqcXsXPyQCgmlkgnY0gmlwhKwSP5OKbXVsdGlhZGRyc5YACASsEj-TBhO-AAoErBI_kwYTv90DgnJzhQADAQAAiXNlY3AyNTZrMaEDFBMIgiTjN12wL4Pq5HL7OvVHngSmBRcmIrRFiOujXuaDdGNwghO-g3VkcIITwIV3YWt1MgE"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2024-12-11_04-05-16__d94d5ae1-5ff9-401b-95f7-50da32309128__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.31.206
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['46850', '46851', '46852', '46853', '46854']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes ['/home/runner/work/waku-interop-tests/waku-interop-tests/rln_tree_mdne_2:/etc/rln_tree', '/home/runner/work/waku-interop-tests/waku-interop-tests/keystore_mdne_2:/keystore']
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 46850:46850 -p 46851:46851 -p 46852:46852 -p 46853:46853 -p 46854:46854 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=46852 --rest-port=46850 --tcp-port=46851 --discv5-udp-port=46853 --rest-address=0.0.0.0 --nat=extip:172.18.31.206 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=6fa24cbedc08e4c49fb16b2741dddab6f3d96cbdece87af56fdfc1cf84e71aab --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=46854 --metrics-logging=true --relay=true --discv5-bootstrap-node=enr:-L24QMVtg9LKpBfmGdIgl1_TDUUdV9c8MgkR0iatA7c8WPeUJ03hSNwYqNv44B8xmPSHJE1c4bTiB8YM5rvqcXsXPyQCgmlkgnY0gmlwhKwSP5OKbXVsdGlhZGRyc5YACASsEj-TBhO-AAoErBI_kwYTv90DgnJzhQADAQAAiXNlY3AyNTZrMaEDFBMIgiTjN12wL4Pq5HL7OvVHngSmBRcmIrRFiOujXuaDdGNwghO-g3VkcIITwIV3YWt1MgE --rln-relay-membership-index=1 --rln-relay-user-message-limit=3 --rln-relay-epoch-sec=1 --rln-relay=true --rln-relay-cred-path=/keystore/keystore.json --rln-relay-cred-password=password
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.31.206 waku 4b15bd5dc7c9c3bf6b55605638fd753fa320572a358c97cd96878a5536770c74
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 4b15bd5dc7c9. Setting up logs at ./log/docker/node2_2024-12-11_04-05-16__d94d5ae1-5ff9-401b-95f7-50da32309128__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 46850
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:46850/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[{"Rln Relay":"Ready"}]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:46850/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.31.206/tcp/46851/p2p/16Uiu2HAm15c7sLHWEyUTdbccCewr8mfSodsrmuZaH9k4ArkF4kBQ","/ip4/172.18.31.206/tcp/46852/ws/p2p/16Uiu2HAm15c7sLHWEyUTdbccCewr8mfSodsrmuZaH9k4ArkF4kBQ"],"enrUri":"enr:-L24QCtdBCByI_onFLaPiWDEjOI8byXmKyY_9if8M1Pm4RlFKoKq4DZO5ZL1TSUIoKket4MctAPFLQP9xdWCzgGuNpoCgmlkgnY0gmlwhKwSH86KbXVsdGlhZGRyc5YACASsEh_OBrcDAAoErBIfzga3BN0DgnJzhQADAQAAiXNlY3AyNTZrMaECVAIj1hU_pUkzOk-9gej-owEZi7xCFFe9FQLp9Zv7AF-DdGNwgrcDg3VkcIK3BYV3YWt1MgE"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:46850/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.63.147/tcp/5054/p2p/16Uiu2HAmE1MLYBpLk7UXCYXfrp6sk1xySh7xGY4LRKKbHvCXbUu3"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:5053/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/1/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:46850/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/1/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m tests.relay.test_rln:test_rln.py:128 Running test with payload A simple string
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:5053/relay/v1/messages/%2Fwaku%2F2%2Frs%2F1%2F0" -H "Content-Type: application/json" -d '{"payload": "SGVsbG8gV29ybGQh", "contentTopic": "/test/1/waku-rln-relay/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m tests.relay.test_rln:test_rln.py:128 Running test with payload An integer
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:5053/relay/v1/messages/%2Fwaku%2F2%2Frs%2F1%2F0" -H "Content-Type: application/json" -d '{"payload": "MTIzNDU2Nzg5MA==", "contentTopic": "/test/1/waku-rln-relay/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m tests.relay.test_rln:test_rln.py:128 Running test with payload A dictionary
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:5053/relay/v1/messages/%2Fwaku%2F2%2Frs%2F1%2F0" -H "Content-Type: application/json" -d '{"payload": "eyJrZXkiOiAidmFsdWUifQ==", "contentTopic": "/test/1/waku-rln-relay/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id aac8c52d323f
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 4b15bd5dc7c9
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container aac8c52d323f. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.