[35mDEBUG   [0m tests.conftest:conftest.py:43 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:49 Running test: test_store_lightpushed_message with id: 2024-05-17_03-20-43__82bec9b1-0f36-41fa-9040-4176044ffaf3
[35mDEBUG   [0m src.steps.common:common.py:15 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.store:store.py:26 Running fixture setup: store_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/publishing_node1_2024-05-17_03-20-43__82bec9b1-0f36-41fa-9040-4176044ffaf3__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.13.80
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['11203', '11204', '11205', '11206', '11207']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:345 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:114 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:116 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 11203:11203 -p 11204:11204 -p 11205:11205 -p 11206:11206 -p 11207:11207 harbor.status.im/wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=11205 --rest-port=11203 --tcp-port=11204 --discv5-udp-port=11206 --rest-address=0.0.0.0 --nat=extip:172.18.13.80 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=11207 --metrics-logging=true --store=true --relay=true --lightpush=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.13.80 waku 2b22d7571c60ae048de1922184e027e8c19ad578462c88c3592d49c640033f55
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 2b22d7571c60. Setting up logs at ./log/docker/publishing_node1_2024-05-17_03-20-43__82bec9b1-0f36-41fa-9040-4176044ffaf3__harbor.status.im_wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Started container from image harbor.status.im/wakuorg/nwaku:latest. REST: 11203
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:11203/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:209 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:11203/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.13.80/tcp/11204/p2p/16Uiu2HAm8Tsju3jHqG2toVi9BCMN6sYExgrJLPKr1WfEf2VYM1XJ","/ip4/172.18.13.80/tcp/11205/ws/p2p/16Uiu2HAm8Tsju3jHqG2toVi9BCMN6sYExgrJLPKr1WfEf2VYM1XJ"],"enrUri":"enr:-LO4QDcQh64srmoWy0D_wcnvi5K5N1MHliXQ9ZdVn8mlvD8XMctFUMOCD1ZNKGMcsTgn4dShvUWAiImGZ85-V3znpsMBgmlkgnY0gmlwhKwSDVCKbXVsdGlhZGRyc4wACgSsEg1QBivF3QOCcnOFAAABAACJc2VjcDI1NmsxoQLBuGOjp3GBKcvMOchtNKco0qKMBcP3Ttp8RtbjF1sGrYN0Y3CCK8SDdWRwgivGhXdha3UyCw"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:214 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image harbor.status.im/wakuorg/go-waku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:48 WakuNode instance initialized with log path ./log/docker/store_node1_2024-05-17_03-20-43__82bec9b1-0f36-41fa-9040-4176044ffaf3__harbor.status.im_wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:52 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.76.189
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['29216', '29217', '29218', '29219', '29220']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:345 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:114 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:116 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 29216:29216 -p 29217:29217 -p 29218:29218 -p 29219:29219 -p 29220:29220 harbor.status.im/wakuorg/go-waku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=DEBUG --rest-relay-cache-capacity=100 --websocket-port=29218 --rest-port=29216 --tcp-port=29217 --discv5-udp-port=29219 --rest-address=0.0.0.0 --nat=extip:172.18.76.189 --peer-exchange=true --discv5-discovery=true --cluster-id=0 --min-relay-peers-to-publish=1 --rest-filter-cache-capacity=50 --discv5-bootstrap-node=enr:-LO4QDcQh64srmoWy0D_wcnvi5K5N1MHliXQ9ZdVn8mlvD8XMctFUMOCD1ZNKGMcsTgn4dShvUWAiImGZ85-V3znpsMBgmlkgnY0gmlwhKwSDVCKbXVsdGlhZGRyc4wACgSsEg1QBivF3QOCcnOFAAABAACJc2VjcDI1NmsxoQLBuGOjp3GBKcvMOchtNKco0qKMBcP3Ttp8RtbjF1sGrYN0Y3CCK8SDdWRwgivGhXdha3UyCw --storenode=/ip4/172.18.13.80/tcp/11204/p2p/16Uiu2HAm8Tsju3jHqG2toVi9BCMN6sYExgrJLPKr1WfEf2VYM1XJ --store=false --relay=false --lightpush=true --lightpushnode=/ip4/172.18.13.80/tcp/11204/p2p/16Uiu2HAm8Tsju3jHqG2toVi9BCMN6sYExgrJLPKr1WfEf2VYM1XJ
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.76.189 waku bd40a026fb2c231e3d1f858fa99135d14373c786b2202857707792499919e428
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID bd40a026fb2c. Setting up logs at ./log/docker/store_node1_2024-05-17_03-20-43__82bec9b1-0f36-41fa-9040-4176044ffaf3__harbor.status.im_wakuorg_go-waku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:122 Started container from image harbor.status.im/wakuorg/go-waku:latest. REST: 29216
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:29216/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"enrUri":"enr:-Ly4QEpB9TxlogzZC0HdBDkwWr7U6aq5fZYr9MAuyE0lDWKiZX2XF0eqnjkwLXX1ftDnXUI_bs7EU1zdqiYmEaJOLCeGAY-EkP2NgmlkgnY0gmlwhKwRAAOKbXVsdGlhZGRyc5gACgSsEQADBnIi3QMACgR_AAABBnIi3QOJc2VjcDI1NmsxoQJkbKjOCZXljGWxXRhX58VYiS60nqWLEePeAMD6RnWKw4N0Y3CCciGDdWRwgnIjhXdha3UyCA","listenAddresses":["/ip4/127.0.0.1/tcp/29217/p2p/16Uiu2HAm2BgrBGSsoJA76dtq7NHPJs42amNpxpPf4gi3ZjGMFfhC","/ip4/127.0.0.1/tcp/29218/ws/p2p/16Uiu2HAm2BgrBGSsoJA76dtq7NHPJs42amNpxpPf4gi3ZjGMFfhC","/ip4/172.17.0.3/tcp/29217/p2p/16Uiu2HAm2BgrBGSsoJA76dtq7NHPJs42amNpxpPf4gi3ZjGMFfhC","/ip4/172.17.0.3/tcp/29218/ws/p2p/16Uiu2HAm2BgrBGSsoJA76dtq7NHPJs42amNpxpPf4gi3ZjGMFfhC"]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:214 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:29216/admin/v1/peers" -H "Content-Type: application/json" -d '{"multiaddr": "/ip4/172.18.13.80/tcp/11204/p2p/16Uiu2HAm8Tsju3jHqG2toVi9BCMN6sYExgrJLPKr1WfEf2VYM1XJ", "protocols": ["/vac/waku/relay/2.0.0"], "shards": [0, 1, 2, 3, 4, 5, 6, 7, 8]}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'null'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:11203/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/0/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:29216/lightpush/v1/message" -H "Content-Type: application/json" -d '{"pubsubTopic": "/waku/2/rs/0/0", "message": {"payload": "U3RvcmUgd29ya3MhIQ==", "contentTopic": "/myapp/1/latest/proto", "timestamp": 1715916046856516352}}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'true'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.store:store.py:151 Checking that peer harbor.status.im/wakuorg/nwaku:latest can find the stored message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:11203/store/v1/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F0%2F0&pageSize=5&ascending=true" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"messages":[{"payload":"U3RvcmUgd29ya3MhIQ==","content_topic":"/myapp/1/latest/proto","version":0,"timestamp":1715916046856516352,"ephemeral":false}]}'
[35mDEBUG   [0m src.steps.store:store.py:151 Checking that peer harbor.status.im/wakuorg/go-waku:latest can find the stored message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:29216/store/v1/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F0%2F0&pageSize=5&ascending=true" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"messages":[{"payload":"U3RvcmUgd29ya3MhIQ==","contentTopic":"/myapp/1/latest/proto","version":0,"timestamp":1715916046856516352}]}'
[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:75 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:169 Stopping container with id 2b22d7571c60
[35mDEBUG   [0m src.node.waku_node:waku_node.py:172 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:169 Stopping container with id bd40a026fb2c
[35mDEBUG   [0m src.node.waku_node:waku_node.py:172 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:32 Running fixture teardown: set_allure_env_variables