[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_main_node_only_relay__peer_relay_and_store with id: 2024-08-16_04-32-32__1a58d413-d955-4b8a-8ea1-e18ee5fdeea6
[35mDEBUG   [0m src.steps.common:common.py:17 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.store:store.py:29 Running fixture setup: store_setup
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:84 WakuNode instance initialized with log path ./log/docker/publishing_node1_2024-08-16_04-32-32__1a58d413-d955-4b8a-8ea1-e18ee5fdeea6__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:88 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.140.113
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['5018', '5019', '5020', '5021', '5022']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:429 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:161 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:163 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 5018:5018 -p 5019:5019 -p 5020:5020 -p 5021:5021 -p 5022:5022 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=5020 --rest-port=5018 --tcp-port=5019 --discv5-udp-port=5021 --rest-address=0.0.0.0 --nat=extip:172.18.140.113 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=5022 --metrics-logging=true --store=false --relay=true --nodekey=30348dd51465150e04a5d9d932c72864c8967f806cce60b5d26afeca1e77eb68
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.140.113 waku d571bec084f635a41f65739f29f713e41e879c92f7d938702d28f2d00225635e
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID d571bec084f6. Setting up logs at ./log/docker/publishing_node1_2024-08-16_04-32-32__1a58d413-d955-4b8a-8ea1-e18ee5fdeea6__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:175 Started container from image wakuorg/nwaku:latest. REST: 5018
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:5018/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:275 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:5018/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.140.113/tcp/5019/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip","/ip4/172.18.140.113/tcp/5020/ws/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"],"enrUri":"enr:-LO4QLYO-a0_J0QR1HTTdJB78azUHHKSlIYyazr9AFNkIRxiJitkKwfQZOiAMcVRtAbGMfkLHUxVhrovgMjXIOlxdr4BgmlkgnY0gmlwhKwSjHGKbXVsdGlhZGRyc4wACgSsEoxxBhOc3QOCcnOFAAMBAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCE5uDdWRwghOdhXdha3UyAQ"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:280 REST service is ready !!
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:17 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:84 WakuNode instance initialized with log path ./log/docker/store_node1_2024-08-16_04-32-32__1a58d413-d955-4b8a-8ea1-e18ee5fdeea6__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:88 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:20 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:23 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:80 Generated random external IP 172.18.41.106
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:73 Generated ports ['39403', '39404', '39405', '39406', '39407']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:429 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:161 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:163 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:47 docker run -i -t -p 39403:39403 -p 39404:39404 -p 39405:39405 -p 39406:39406 -p 39407:39407 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=39405 --rest-port=39403 --tcp-port=39404 --discv5-udp-port=39406 --rest-address=0.0.0.0 --nat=extip:172.18.41.106 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=39407 --metrics-logging=true --discv5-bootstrap-node=enr:-LO4QLYO-a0_J0QR1HTTdJB78azUHHKSlIYyazr9AFNkIRxiJitkKwfQZOiAMcVRtAbGMfkLHUxVhrovgMjXIOlxdr4BgmlkgnY0gmlwhKwSjHGKbXVsdGlhZGRyc4wACgSsEoxxBhOc3QOCcnOFAAMBAACJc2VjcDI1NmsxoQM3Tqpf5eFn4Jztm4gB0Y0JVSJyxyZsW8QR-QU5DZb-PYN0Y3CCE5uDdWRwghOdhXdha3UyAQ --storenode=/ip4/172.18.140.113/tcp/5019/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip --store=true --relay=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:53 docker network connect --ip 172.18.41.106 waku 1c80fce65ebadce17baa759aa613ad89cd57adaf623dd1885a42927fa7a3ad91
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:56 Container started with ID 1c80fce65eba. Setting up logs at ./log/docker/store_node1_2024-08-16_04-32-32__1a58d413-d955-4b8a-8ea1-e18ee5fdeea6__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:175 Started container from image wakuorg/nwaku:latest. REST: 39403
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:39403/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:275 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:39403/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.41.106/tcp/39404/p2p/16Uiu2HAm6zrHuaAD88XaeHCFToy9qnr7UosWucHgHYUTFU2ZadMo","/ip4/172.18.41.106/tcp/39405/ws/p2p/16Uiu2HAm6zrHuaAD88XaeHCFToy9qnr7UosWucHgHYUTFU2ZadMo"],"enrUri":"enr:-LO4QFA6fBBQgzlEgvm-cePqsNlBnb6eWM9k8rshQRWNc48hOJXwmtBmBr2Op9eE4M4fYP5_QG6ZoFVfiDSHov44-WUBgmlkgnY0gmlwhKwSKWqKbXVsdGlhZGRyc4wACgSsEilqBpnt3QOCcnOFAAMBAACJc2VjcDI1NmsxoQKr8GIPkvQ8I6DmHrmp1ZkG_ciQgHbphLFfnp5R8SwUToN0Y3CCmeyDdWRwgpnuhXdha3UyAw"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:280 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:39403/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.140.113/tcp/5019/p2p/16Uiu2HAmGNtM2rQ8abySFNhqPDFY4cmfAEpfo9Z9fD3NekoFR2ip"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:5018/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:39403/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/0"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.store:store.py:129 Relaying message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:5018/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F0" -H "Content-Type: application/json" -d '{"payload": "U3RvcmUgd29ya3MhIQ==", "contentTopic": "/myapp/1/latest/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.2 seconds
[35mDEBUG   [0m src.steps.store:store.py:217 Checking that peer wakuorg/nwaku:latest can find the stored message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:39403/store/v3/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F3%2F0&pageSize=5&ascending=true" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"","statusCode":200,"statusDesc":"OK","messages":[{"messageHash":"zqIUjZsVpkz0a6IC8kuBS0cXkiZA5sNBeRhGsY+So88="}]}'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:219 Stopping container with id d571bec084f6
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:219 Stopping container with id 1c80fce65eba
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Container stopped.